### ISSUE TITLE
Segmentation fault after sampling and clustering

### ISSUE THREAD

**Issue by qhz991029** [HeracleBT/CryoAlign#1]
Thank you for your great work!

I am trying to use CryoAlign to fit two density maps, but I always get segmentation fault after sampling and clustering of the second density map. It is `os.system("alignment/point_cloud_feature %s %s %s %.2f > %s" % (points_dir, normal_dir, key_points_dir, radius, feature_dir))` in `Utils.py` that caused the segmentation fault. I have tried to use point_cloud_feature in the repo as well as the one built by myself, but I still have the same issue. 

I wonder is there anything to be careful with about the point_cloud_feature, what could be the potential reason.

Best regards.

**Comment by HeracleBT** [comment]
Maybe you can check the point cloud files (.pcd) and normals (.txt) in the "EMD***-EMD***/temp" directory. 
The .pcd file should look like the following:
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z
SIZE 4 4 4
TYPE F F F
COUNT 1 1 1
WIDTH 20178
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 20178
DATA ascii
-145.00000 -5.00000 15.00000
-145.00000 10.00000 5.00000
-145.00000 10.00000 10.00000
-145.00000 15.00000 10.00000
-145.00000 15.00000 15.00000
```
And normals (.txt) as:
```
0.92061 -0.36931 0.12682
0.79911 0.06598 0.59756
0.88441 0.46485 -0.04161
0.94696 0.06539 0.31464
0.70163 0.08509 -0.70744
```
Noted that, the numbers of points and corresponding normals should be matched.
