### ISSUE TITLE
Not all files are in the data folder

### ISSUE THREAD

**Issue by davidheisenberg** [HeracleBT/CryoAlign#2]
Hello,

I am testing CryoAlign, but I ran into a problem. When trying to run the example commands in the README, some files are missing. For example, I do not see any .map files in data/emd_3695_3696.

It may be beneficial to update the data folder so new users could verify the program is working correctly more quickly.

Thanks!

**Comment by HeracleBT** [comment]
I‘m sorry not to upload all files. Actually, .map file is the volume data provided by EMDB. The file is large and you can download it from the link like [https://www.ebi.ac.uk/emdb/EMD-3696)，](https://www.ebi.ac.uk/emdb/EMD-3696)%EF%BC%8C)

**Comment by davidheisenberg** [comment]
Got it, thanks!
